/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as PatientsVisitorsRouteImport } from './routes/patients-visitors'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DepartmentsIndexRouteImport } from './routes/departments.index'
import { Route as DepartmentsIdRouteImport } from './routes/departments.$id'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as DoctorsIdRouteImport } from './routes/doctors.$id'
import { Route as HealthLibraryIndexRouteImport } from './routes/health-library.index'
import { Route as HealthLibrarySlugRouteImport } from './routes/health-library.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsVisitorsRoute = PatientsVisitorsRouteImport.update({
  id: '/patients-visitors',
  path: '/patients-visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIdRoute = DepartmentsIdRouteImport.update({
  id: '/departments/$id',
  path: '/departments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIdRoute = DoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthLibraryIndexRoute = HealthLibraryIndexRouteImport.update({
  id: '/health-library/',
  path: '/health-library/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthLibrarySlugRoute = HealthLibrarySlugRouteImport.update({
  id: '/health-library/$slug',
  path: '/health-library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/facilities': typeof FacilitiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/insurance': typeof InsuranceRoute
  '/patients-visitors': typeof PatientsVisitorsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/health-library/$slug': typeof HealthLibrarySlugRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/health-library/': typeof HealthLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/facilities': typeof FacilitiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/insurance': typeof InsuranceRoute
  '/patients-visitors': typeof PatientsVisitorsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/health-library/$slug': typeof HealthLibrarySlugRoute
  '/departments': typeof DepartmentsIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/health-library': typeof HealthLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/facilities': typeof FacilitiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/insurance': typeof InsuranceRoute
  '/patients-visitors': typeof PatientsVisitorsRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/health-library/$slug': typeof HealthLibrarySlugRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/health-library/': typeof HealthLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointment'
    | '/careers'
    | '/contact'
    | '/emergency'
    | '/facilities'
    | '/faq'
    | '/gallery'
    | '/insurance'
    | '/patients-visitors'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/departments/$id'
    | '/doctors/$id'
    | '/health-library/$slug'
    | '/departments/'
    | '/doctors/'
    | '/health-library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointment'
    | '/careers'
    | '/contact'
    | '/emergency'
    | '/facilities'
    | '/faq'
    | '/gallery'
    | '/insurance'
    | '/patients-visitors'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/departments/$id'
    | '/doctors/$id'
    | '/health-library/$slug'
    | '/departments'
    | '/doctors'
    | '/health-library'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointment'
    | '/careers'
    | '/contact'
    | '/emergency'
    | '/facilities'
    | '/faq'
    | '/gallery'
    | '/insurance'
    | '/patients-visitors'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/departments/$id'
    | '/doctors/$id'
    | '/health-library/$slug'
    | '/departments/'
    | '/doctors/'
    | '/health-library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentRoute: typeof AppointmentRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  EmergencyRoute: typeof EmergencyRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  InsuranceRoute: typeof InsuranceRoute
  PatientsVisitorsRoute: typeof PatientsVisitorsRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  DepartmentsIdRoute: typeof DepartmentsIdRoute
  DoctorsIdRoute: typeof DoctorsIdRoute
  HealthLibrarySlugRoute: typeof HealthLibrarySlugRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  HealthLibraryIndexRoute: typeof HealthLibraryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients-visitors': {
      id: '/patients-visitors'
      path: '/patients-visitors'
      fullPath: '/patients-visitors'
      preLoaderRoute: typeof PatientsVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$id': {
      id: '/departments/$id'
      path: '/departments/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof DepartmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$id': {
      id: '/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof DoctorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-library/': {
      id: '/health-library/'
      path: '/health-library'
      fullPath: '/health-library/'
      preLoaderRoute: typeof HealthLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-library/$slug': {
      id: '/health-library/$slug'
      path: '/health-library/$slug'
      fullPath: '/health-library/$slug'
      preLoaderRoute: typeof HealthLibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentRoute: AppointmentRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  EmergencyRoute: EmergencyRoute,
  FacilitiesRoute: FacilitiesRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  InsuranceRoute: InsuranceRoute,
  PatientsVisitorsRoute: PatientsVisitorsRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  DepartmentsIdRoute: DepartmentsIdRoute,
  DoctorsIdRoute: DoctorsIdRoute,
  HealthLibrarySlugRoute: HealthLibrarySlugRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  HealthLibraryIndexRoute: HealthLibraryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
